/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ilatypov' at '23.08.16 9:24' with Gradle 2.4
 *
 * @author ilatypov, @date 23.08.16 9:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
